# NUMPY

In [ ]:
# It is also a data structure like list, tuple, set .i.e a collection of element's. As already there are list, tuple etc 
# then why there iis need of Numpy -- generally complex operation, scientific operation, statistic's , boolean algebra iske
# jo examples hai, expression usko solve karnekeliye Numpy is necessary. It has many built in functionalities -- eg SD, mean
# mode, median, wo hum easily calculate kar sakte hai -- bcz numpy main wo already code likhake rakha hai.
# In short numpy complex mathematical problem/ expression ko solve karnekeliye Numpy built hua hai.
# Fullform of Numpy is Numerical Python.
# Numpy is faster than list, tuple. Compplex Operation's can be perform fastly with the help of Numpy -- Why we use Numpy?
# It is faster because it is lightweight so consume less memory, It is written(built) in "C" language which is faster.
# List and tuple main hume controll nahi rehta ki exactally kitne bytes ka element banana hai but Numpy we can specify for 
# aapka data two digit hai to hum specify kar sakte hai ki usko jo memory space allocate hoga wo sum bit ka allocate hoga.
# isase equivalent block of memory create hoti hai.
# It's operation's are similar to operation's on list and tuple -- It is an also data structure like that 
# Numpy pandas ke sath aa jata hai inbuild so no need to install it seperately

In [ ]:
# Certainly! NumPy, short for "Numerical Python," is a powerful Python library for numerical and mathematical operations. 
# It provides support for working with large, multi-dimensional arrays and matrices, along with a collection of mathematical
# functions to operate on these arrays. Here's a breakdown of its key features and uses:

# 1. **Arrays:** NumPy introduces a new data type called "numpy.ndarray," which is essentially an array or grid of values.
#             These arrays can be one-dimensional (like a list), two-dimensional (like a table or matrix), or even higher
#             -dimensional.

# 2. **Efficient Computation:** NumPy is designed for numerical computations and is highly optimized for speed and 
#                            efficiency. It allows you to perform operations on entire arrays at once, making it much faster
#                            than using standard Python lists for mathematical tasks.

# 3. **Mathematical Operations:** You can perform a wide range of mathematical operations on NumPy arrays, including 
#                              addition, subtraction, multiplication, division, exponentiation, and more. These operations 
#                              can be applied element-wise or using matrix algebra.

# 4. **Broadcasting:** NumPy includes a powerful feature called broadcasting, which allows you to perform operations on
#                   arrays with different shapes. It automatically aligns and expands smaller arrays to match the shape
#                   of larger arrays, making complex calculations more straightforward.

# 5. **Random Number Generation:** NumPy includes functions for generating random numbers and random data, which is 
#                                essential for various applications in statistics, simulations, and machine learning.

# 6. **Linear Algebra:** It provides extensive support for linear algebra operations like matrix multiplication, 
#                     determinants, eigenvalues, and more. This makes it invaluable for scientific computing and data
#                     analysis.

# 7. **Integration with Other Libraries:** NumPy seamlessly integrates with other popular data science and scientific
#                                       computing libraries, such as SciPy, pandas, and scikit-learn, making it a 
#                                       fundamental building block for many data-related tasks.

# In summary, NumPy is a fundamental library for numerical computing in Python. It enables efficient manipulation and 
# analysis of numerical data, making it an essential tool for tasks involving mathematics, data analysis, machine learning,
# and scientific research.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
# How to create numpy array -- array is collection of similar type of data -- isme similar type ka data hota hai -- means 
# agar integer ka data hoga to sab integer type ka data hoga means homogenous type ka data
# How to create array
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
type(a) # nd means n dimesional array

numpy.ndarray

In [ ]:
# Jaise hum list, tuple only 1D create kar sakte hai but Numpy main hum we can create ND  -- N dimensional 1D, 2D, 3D jitne
# bhi dimension ka data create karna hai we can create with the help of numpy array
# Generally numpy is used for matrix calculation
# Inbuild operations are maximum in numpy
# In simple language, a matrix in NumPy is like a grid of numbers. Think of it as a table or a spreadsheet with rows and 
# columns, where each cell can hold a number. You can use these matrices to do math, like adding, subtracting, or
# multiplying the numbers inside them. Matrices are handy when you want to work with structured data or perform 
# mathematical operations on organized sets of numbers.

In [5]:
# just like list we can access elements of numpy using indexing
a[0]

1

In [ ]:
# A multidimensional array in NumPy is like a supercharged list of numbers that can have multiple rows and columns, just 
# like a table. 
# Here's a simple way to understand it:
# - A one-dimensional array is like a list of numbers.
# - A two-dimensional array is like a table with rows and columns.
# - A three-dimensional array is like a collection of tables stacked on top of each other.
# You can keep adding dimensions to create even more complex structures. These multidimensional arrays are incredibly 
# useful for various mathematical and data manipulation tasks because they allow you to organize and work with data in
# a structured way.

In [2]:
# How to create two dimensional array containing row's and column
# Creating a two-dimensional array (also known as a matrix) in NumPy is quite straightforward. You can use the numpy.array()
# function or other NumPy functions like numpy.zeros() or numpy.ones().
# Here are some examples:
# 1.Using numpy.array():
d = np.array([[1,2,3,4],[5,6,7,8]])
d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
# 2.Using numpy.zeros() to create an array filled with zeros:
# Create a 2D array filled with zeros, for example, a 3x4 array
zeros_array = np.zeros((3, 4))

# Display the zeros array
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
# Using numpy.ones() to create an array filled with ones
# Create a 2D array filled with ones, for example, a 2x2 array
ones_array = np.ones((2, 2))

# Display the ones array
print(ones_array)

[[1. 1.]
 [1. 1.]]


In [4]:
d.shape #indicate that there are two row's and four column's

(2, 4)

In [7]:
d.dtype # to see the data type of the values -- usme konsa data wo dekhane keliye -- show usme integer data hai
# it shows ek element main kitna memory occupy kiya hai wo dikhata hai

dtype('int32')

In [ ]:
# In NumPy, the dtype (data type) function is used to specify and check the data type of elements stored in a NumPy array. 
# Each element in a NumPy array has a specific data type, which determines how the data is stored in memory and how it
# behaves during mathematical operations.

In [5]:
# 1.Specify Data Type when Creating an Array:
# You can specify the data type of the elements when creating a NumPy array using the dtype parameter. For example:
# Create an array of integers
int_array = np.array([1, 2, 3], dtype=np.int32)

# Create an array of floating-point numbers
float_array = np.array([1.0, 2.0, 3.0], dtype=np.float64)
float_array

array([1., 2., 3.])

In [6]:
# 2.Check the Data Type of an Existing Array:
# You can use the dtype attribute to check the data type of an existing NumPy array:
my_array = np.array([1, 2, 3])

# Check the data type of my_array
data_type = my_array.dtype
data_type

dtype('int32')

In [ ]:
# Common data types in NumPy include integers (int or uint for signed and unsigned integers), floating-point numbers 
# (float), complex numbers (complex), and others like bool, str, etc. Specifying the correct data type is important for
# memory efficiency and ensuring that operations are performed correctly on the array's elements.

In [8]:
# agar item size dekhana hai ki kitne byte ka hai then
d.itemsize  # 1 byte = 8 bit  so 32 bit means 4 bytes

4

In [ ]:
# In NumPy, the itemsize attribute is used to determine the size (in bytes) of each element in a NumPy array. This can be
# helpful when you want to know how much memory an array consumes or when you need to work with low-level memory operations.

In [7]:
# Here's how you can use the itemsize attribute:
# Create an array of integers
my_array = np.array([1, 2, 3], dtype=np.int32)

# Get the size of each element in bytes
element_size = my_array.itemsize

# Print the element size
element_size
# In this example, element_size will give you the size (in bytes) of each element in the my_array. This is particularly 
# useful when dealing with large arrays or when you need to interact with external libraries or memory management.
# So here one element is consuming 4 bytes memory.

4

In [ ]:
# Keep in mind that different data types have different sizes, so the itemsize will vary depending on the data type you 
# specify for your array. For example, an array of 32-bit integers (np.int32) will have an itemsize of 4 bytes, while an
# array of 64-bit floating-point numbers (np.float64) will have an itemsize of 8 bytes.

In [11]:
# In NumPy, the size attribute is used to determine the total number of elements in a NumPy array. It provides the count
# of all the items in the array, regardless of its shape or dimensionality.
# Here's how you can use the size attribute:

# Create a 2D array (matrix)
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Get the total number of elements in the matrix
total_elements = matrix1.size

# Print the total number of elements
total_elements
# In this example, total_elements will give you the count of all elements in the matrix, which is 9 in this case because
# there are 9 numbers in the 3x3 matrix.
# The size attribute is useful when you need to know the overall size of your NumPy array, especially when working with
# larger datasets or when performing operations that depend on the total number of elements.
# In short size attribute will give count of all element's in the numpy array.

9

In [13]:
matrix1.itemsize

4

In [15]:
mem_con = matrix1.itemsize * matrix1.size
mem_con

36

In [10]:
d.itemsize * d.size # This show's total number of bytes occupied 

32

In [11]:
# we have controll over the size for eg we can specify here byte
b = np.array([[1,2,3,4],[5,6,7,8]],dtype = 'int8')
b # means size it occupied is controlled here

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int8)

In [12]:
b.dtype

dtype('int8')

In [13]:
b.itemsize # here one element ne 1 byte consume kiya

1

In [14]:
b.size * b.itemsize # total bytes consume by the array are 8 as one item consume one byte -- so in array memory consumption
# can be controlled which is not possible in the list

8

In [15]:
# let's see memory consume by the list
import sys
temp = [23,45,67,43,76,98,23]
sys.getsizeof(23) # so here one value consume 28 bytes that's why numpy array is preferable

28

In [16]:
sys.getsizeof(23)*len(temp) # so in total the entire list consume 196 bytes -- so list is heavy weight

196

In [ ]:
# 8 bit's means 1 byte for eg here 1  can be place in 1 byte also in 2 byte also in 3 bytes
1 byte = 0 0 0 0 0 0 0 1
2 byte = 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
3 byte = 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 # This is unnecessary
# just bit's are increasing nothing else

In [17]:
# how to check dimension of array
b.ndim # so it gives result that 2 dimension data

2

In [ ]:
# In the context of arrays and data structures, a dimension refers to a specific axis along which data is organized. It 
# represents one direction along which elements are arranged within the array.
# In simpler terms:
# A one-dimensional array is like a list, where elements are arranged along a single line. You can think of it as a row of
# elements.
# A two-dimensional array is like a table or grid, where elements are arranged in rows and columns. It has two dimensions:
#     rows and columns.
# A three-dimensional array is like a cube or a collection of stacked tables, where elements are organized in rows, columns,
# and layers. It has three dimensions: rows, columns, and depth.
# You can keep adding dimensions to create higher-dimensional arrays, which can represent more complex structures in data.
# Dimensions are essential because they define the structure and organization of data within an array. Depending on the 
# dimensionality of an array, you can perform various operations and manipulations to analyze and work with the data 
# effectively. For example, in NumPy, you can use dimensions to access specific elements, slice arrays, and perform 
# mathematical operations along specific axes.

In [ ]:
# DF is collection of row's and column with default indexes( indices ) but actual data column name and index line exclude
# karke jo bachata hai wo hota hai it's nothing but matrix isiko hum (only numerical data -- koi column name nahi kuch nahi
# usko column name kuch pata nahi hota ML algorithm ko wo just aapka jo numerical data hai uspehi algorithm apply karta hai)
# ML algorithm ko pass karte hai. To ye numerical data of DF excluding column name and index is nothing but matrix(row & 
# colum) eg [1,2,3,4],[5,6,7,8] so here this is rows and columns to ispe operation karna hai to at the end hume numpy array
# -pehi operation karna padta hai agar nahi karte ho to ML algorithm usko inbuild convert karkehi leta hai.

In [20]:
# Manlo hume kuch data ko access karna hai for eg specific element hogaya row hogaya column hogaya to same like jaise list 
# mein DF main karte the same waisehi karenge
# Agar mujhe specific element chahiye to yahape row's and column wala funda hai eg b[row,column]
b[1,:] # 1st row humne access kiya agar

array([5, 6, 7, 8], dtype=int8)

In [23]:
# agar hume 0 row access karna hai to
b[1,2:]

array([7, 8], dtype=int8)

In [24]:
# Now I want to access 7 then how to do that
b[1,2]

7

In [25]:
# How to acess 4
b[0,3]

4

In [27]:
# if in list we pass one value as float and remaining as int then by default other value will be converted into float
d = [1,2,3,4,5.3,6]
f = np.array(d)
f

array([1. , 2. , 3. , 4. , 5.3, 6. ])

In [ ]:
# In numpy data will be always in the numerical form in the case of ML
# categorical data hai eg city hai to hum city ko encode karte hai number main, mmanlo gender hai to iskobhi hum encode 
# karte hai 1 or 0 -- to  always hum machine laerning ko hum numerical data dete hai -- categorical data nahi jata

In [28]:
# How to create 3D numpy array
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [29]:
a.ndim # so here three dimensional data create hua

3

In [31]:
a[0,1,1]

5

In [33]:
b = np.array([[[1,2,3],[4,5,6]],[[11,22,33],[7,8,9]]])
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [ 7,  8,  9]]])

In [35]:
a[0,1,1] # because it is like box front square contain 1 st matrix and backside box contain 2nd matrix
# front square 1 st matrix contain 1,2,3,4,5,6 and back square 2nd matrix contain 11,22,33,7,8,9 
# so index of front matrix is 0 and back matrix is 1
# index of rows inside first matrix is 0 and 1 while index of column's are 0,1,2
# FOR EG. [index1, index2, index3]  -- index1 indicate position of matrix, index2 indicate position of rows, 
# index3 indicate position column
# so if I want to access 5 then how I will access it -- it is in 1st matrix 2nd row's , 2nd column.
b[0,1,1]

5

In [36]:
# How to access 9
b[1,1,2]

9

In [38]:
# Generally jab kabhi hume kuch matrix calculation karna hai tab kuch inbuild matrix rehate hai wo useful rehate hai jaise
# manlo aapko once wala, zeros wala ya identity matrix create karna hai to ye bahot useful hota hai kabhi kabhi
# agar koi DF hai usko transform karna hai ya multiply karna hai matrix se tab use hota hai
# for eg
a = np.ones((2,2)) # 2 dimensional data
a 

array([[1., 1.],
       [1., 1.]])

In [39]:
# by default ye float wala de raha hai but mujhe integer wala chahiye then how
a = np.ones((2,2),dtype='int')
a

array([[1, 1],
       [1, 1]])

In [41]:
# How to do three dimension
a = np.ones((3,2,2),dtype='int')
a

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [42]:
# mujhe once wala matrix chahiye 4 dimensionka then how
a = np.ones((4,4),dtype='int')
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [43]:
# agar mujhe 3 by 3 ka matrix chahiye or sabme 20 values chahiye then how
np.full((3,3),20)

array([[20, 20, 20],
       [20, 20, 20],
       [20, 20, 20]])

In [44]:
# Generally numpy main integer or flaot ka hi data rehata hai
# Agar aapko koi random wala matrix chahiye to 
np.random.rand(3,3)

array([[0.12203719, 0.41873767, 0.70927747],
       [0.3074153 , 0.53712888, 0.4874955 ],
       [0.53751528, 0.81207208, 0.46052553]])

In [45]:
# what if I want matrix in the integer using random
np.random.randint(2,3,size=(3,3))

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [46]:
# Identity matrix create karna hai to np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
a+1 # like this we can perform operation on the matrix so the value of entire matrix changes.

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [48]:
temp = np.random.randint(200,600,size=(3,3))
temp

array([[313, 220, 582],
       [517, 560, 520],
       [221, 539, 271]])

In [49]:
# how to get max value from the above matrix -- applying statistic's on matrix
np.max(temp)

582

In [50]:
np.min(temp) # to get min

220

In [51]:
np.sum(temp) # to get sum

3743

In [52]:
np.argmax(temp)

2

In [53]:
# mainly numpy main jyada use hone wala function hai wo hai shape -- reshape karna 
# suppose temp matrix ka size 3 by 3 hai to iska multiplication ka jitnabhi hota hai for 3*3 = 9 hota hai to iske 
# combination main iska reshape ho sakta hai means what one by nine(1,9) , nine by one(9,1) ho sakta hai -- how to do that
# suppose mujhe one by nine reshape karna hai then how
temp.reshape(1,9)

array([[313, 220, 582, 517, 560, 520, 221, 539, 271]])

In [54]:
# create (9,1)
temp.reshape(9,1)

array([[313],
       [220],
       [582],
       [517],
       [560],
       [520],
       [221],
       [539],
       [271]])

In [55]:
# How to convert this array into list -- use type casting
list(temp) # now we can perform list operation's on it

[array([313, 220, 582]), array([517, 560, 520]), array([221, 539, 271])]

In [57]:
# arrange bhi kar sakte hai
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# ab manlo mujhe element ka index chahiye -- suppose mujhe a main se 4 se greater element ka index chahiye not a element
np.where(a>4) # So in output I will get index of elements who are greater than 4 and not the element's itself

(array([5, 6, 7, 8, 9], dtype=int64),)

In [59]:
a = np.array([34,745,24,75,34,86,354,97,35,97])
a

array([ 34, 745,  24,  75,  34,  86, 354,  97,  35,  97])

In [60]:
np.where(a>45) # so in output it is giving the index number and not the value's

(array([1, 3, 5, 6, 7, 9], dtype=int64),)

In [61]:
import pandas as pd

In [63]:
df = pd.DataFrame({'name':['sdf','asdf','asdf'],
                  'id':[101,102,103]})
df

name   id
0   sdf  101
1  asdf  102
2  asdf  103

In [66]:
# Now isko mujhe ek numpy array karna hai then 
p = pd.Series([11,2,3],name = 'test')

In [67]:
pd.concat([df,p],axis=1)

name   id  test
0   sdf  101    11
1  asdf  102     2
2  asdf  103     3

In [ ]:
# Now that will be converted into Series
temp = pd.concat(np.array(3))

In [68]:
temp = np.array([45,754,35])

In [69]:
temp

array([ 45, 754,  35])

In [70]:
pd.Series(temp,name='testd')

0     45
1    754
2     35
Name: testd, dtype: int32

In [72]:
pd.concat([df,pd.Series(temp,name='testd')],axis=1)

name   id  testd
0   sdf  101     45
1  asdf  102    754
2  asdf  103     35

In [ ]:
# Numpy array ko humne pehale series main convert kiya fir usko concat kiya df 

# Numpy By WSCubeTech

In [ ]:
# Numpy is a scientific package for mathematical calculation 
# Numpy gives you a multidimensional array
# Numpy is faster than the list
# Numpy is a python package jiske under hum numpy create karte hai
# Array is a grid jo value ko contain karti hai bahot sari information jobhi aapke pass data hai un data ko collect karneka
# kam karti hai.
# There are multiple types of the array like one dimensional, two dimensional, three dimensional, multidimensional array
# Although array looks like a list but there was a fundamental difference between both of them.
# Array looklike matrix.
# one D Array == [1 2 3 4] -- see SS wscubetech 1st lec 5.12
# array = [1 2 3 4]
          [5 6 7 8]
          [9 0 0 9]
# here shape is (count_of_axis_0, count_of_axis_1)  i.e 3 rows and 4 columns so shape(3,4)
# [1 2 3 4] here shape will be shhape(4,)
# 3 dimensional array shape(4,3,2)

# ADVANTAGES OF USING NUMPY ARRAYS OVER LIST
# -- consumes less memory
# -- fast as compared to python list
# -- convenient to use

# list = [1,2,3,4]
# array = [1 2 3 4]
# list is comma seperated while array is not comma seperated

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [6]:
# How to create array in the numpy
x = np.array([1,2,3,4])
print(x)
type(x)

[1 2 3 4]


numpy.ndarray

In [8]:
# list created here
y = [1,2,3,4]
print(y)
type(y)

[1, 2, 3, 4]


list

In [ ]:
# IMPORTANCE OF NUMPY IN PYTHON
# -- jab hume bahot jyada mathematical calculations perform karne hote hai tab hum numpy arraay use karte hai instead of lst
# -- it supplies an enormous library of high-level mathematical functionss that operate on these arrays and matrices.
# -- mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra,
#    basic statistical operations and much more can be done with the help of the numpy.
# -- huge use in the ML.

In [1]:
import numpy as np

In [3]:
sanket = np.array([1,2,3,4,5])
print(sanket)

[1 2 3 4 5]


In [4]:
# How to know the numpy version
np.__version__

'1.25.2'

In [6]:
# create numpy nd array object
# numpy is use to work with array's and the array's are object in the numpy which is called ndarray
# when we create ndarray then we need to use numpy array function -- for creating the ndarray
# Basic Sytax
sanket = np.array([1,2,3,4,5,6])
print(sanket)

[1 2 3 4 5 6]


In [7]:
type(sanket) # built in function of the python which tells the type of the object you passed to that function.

numpy.ndarray

In [8]:
# create numpy array --you can use any list, tuple, you can also pass the object
# whatever object you will pass in np.array function , it will automatically get converted into the array
sanket = np.array((1,2,3,4,5))
print(sanket)

[1 2 3 4 5]


In [ ]:
## Dimension of Array
# -- Dimension in array is one level of array depth.
# -- nested arrays -- NA are arrays which have arrays as a element means arrays under arrays.

In [9]:
# 0 Dimension Array -- menas no dimension -- each value in an array is an 0 dimensional
sanket = np.array(50)
print(sanket)

50


In [10]:
#  1 Dimension Array -- an array has 0 dimesional array as it's element it is called 1D array. if an array has 
# an array it is called as nested array or the nd array.
sanket = np.array([1,2,3,4,5])
print(sanket)

[1 2 3 4 5]


In [11]:
# 2 Dimension Array -- If an array has an 1 Dimensional array as an element then it is known as a 2 Dimensional Array.
# use in matrix -- like tabular form
sanket = np.array([[1,2,3],[4,5,6]]) # double container
print(sanket)

[[1 2 3]
 [4 5 6]]


In [12]:
# 3 Dimension Array -- If an array has an 2 Dimensional arrays as an element it is known as 3 Dimensional array
sanket = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(sanket)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
sanket = np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])
print(sanket)

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]


In [14]:
type(sanket)

numpy.ndarray

In [16]:
# Checking the number of dimensions -- use np.ndim function for that purpose
np.ndim(sanket)

3

In [17]:
no = np.array(10)
n1 = np.array([1,2,3])
n2 = np.array([[1,2,3],[4,5,6]])
n3 = np.array([[[1,2,3],[4,5,6]]])

In [19]:
np.ndim(no)

0

In [20]:
np.ndim(n1)

1

In [21]:
np.ndim(n2)

2

In [22]:
np.ndim(n3)

3

In [23]:
no.ndim # You can also do by this way

0

In [24]:
# Higher Dimensional Array's. -- an array can have any no of dimensions -- you can define the no of dimensions by using
# ndmin arguments.
sanket = np.array([1,2,3,4],ndmin=5) # If I want to define how many dimesions an array can Have then I can use ndmin 
# function for that purpose -- here I want to create the array with the 5 Dimension and I will clarify that it have 5 
# Dimensions
sanket # It create the 5D array
# here innermost dimension ([1,2,3,4]) is the 5th one -- menas outer parts of the 5th dimension has the 4 elements

array([[[[[1, 2, 3, 4]]]]])

In [25]:
# How to access the elements of the array -- use indexing 
sanket = np.array([1,2,3,4])
# I want to print only 1 then how 
print(sanket[0])

1


In [26]:
# How to print 3
print(sanket[2])

3


In [27]:
# Adding the elements of the numpy array -- add 4 and the 3
print(sanket[2]+sanket[3])

7


In [28]:
# accessing the elemetns of the 2 Dimensional array -- we will use the coomma seperated integers -- just think 2D array like
# a table with rows and the column where dimension represent the row and the index represent the columns.
sanket = np.array([[1,2,3,4,5],[6,7,8,9,10]])
# How to access the 2
print(sanket[0,1]) # row,column

2


In [30]:
# 4rth element of the 1st row
print(sanket[0,3])

4


In [34]:
# Accessing the elements of the 3 Dimensional Array
sanket = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(sanket.ndim)
sanket

3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
# how to access the 3rd element of the 2nd array of the 1st array -- i.e 6
print(sanket[0,1,2]) #matrix,row,column

6


In [38]:
# How to access the elements of the array via negative indexing -- use in the case of large amount of data -- accessing the 
# array from the end
sanket = np.array([[1,2,3,4,5],[6,7,8,9,10]])
sanket

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
# print 10
print(sanket[-1,-1])

10


In [40]:
# print the 8
print(sanket[-1,-3])

8


In [41]:
# How to slice the array -- like we do in the python [start:stop:step] # by default values of the start is 0, stop is end of
# value and the step is 1.
sanket = np.array([1,2,3,4,5,6,7])
print(sanket[1:5])

[2 3 4 5]


In [42]:
# slicing from 4 to the end
print(sanket[4:])

[5 6 7]


In [43]:
# slice the elements from 1st to the 4
print(sanket[0:4])

[1 2 3 4]


In [44]:
# Negataive slicing
# slice from end 3
print(sanket[-3:-1])

[5 6]


In [45]:
# return every second element from the array
print(sanket[::2])

[1 3 5 7]


In [46]:
# Slicing the 2D Array
sanket = np.array([[1,2,3,4,5],[6,7,8,9,10]])
# slice from 1 to 4
print(sanket[1,1:4])

[7 8 9]


In [47]:
# How to access from the both elements -- how to access 3,8 at the same time
print(sanket[0:2,2]) # I have use rows slicing here

[3 8]


In [49]:
# from both rows we will slice 1 to 4 index
print(sanket[0:2,1:4])

[[2 3 4]
 [7 8 9]]


# Data Types in Python Numpy

In [ ]:
# Numpy has some extra data types and we actually refer this datatypes to one character
# like i for integer, b for boolean, f for float, c for complex etc.
# the numpy array object has the property which is called dtype and that returns the datatype of an array

In [52]:
sanket = np.array([1,2,3,4,5])
print(sanket.dtype) # ineteger datatype of 32 bit of data

int32


In [53]:
sanket = np.array(['apple','banana','cherry'])
print(sanket.dtype) # it will give data type U6

<U6


In [55]:
# If you want to create an array with the defined data type in the numpy then you can create so. use dtype to pass datatype
sanket = np.array([1,2,3,4],dtype='S') # here S indicate the string so S is use to define datatype 
print(sanket)
print(sanket.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [57]:
# You can also  speciify the bytes also -- create an array with a dtype int with 4 bytes
sanket = np.array([1,2,3,4],dtype='i4')
print(sanket)
print(sanket.dtype)

[1 2 3 4]
int32


In [58]:
# value error ooccured when an type of argument pass to a function is an incorrect.
sanket = np.array(['a','2','3'],dtype='i') # Here a cannot be converted into the numerical type
print(sanket)

ValueError: invalid literal for int() with base 10: 'a'

In [60]:
# converting datatype on an existing arrays - astype()
# we will change the datatype from the float to integer by using 'i'
sanket = np.array([1.1,2.1,3.1])
sanketcopy = sanket.astype('i')
print(sanketcopy)
print(sanket.dtype)
print(sanketcopy.dtype) # we change the dtype by creating the copy

[1 2 3]
float64
int32


In [61]:
# Change datatype from integer to the boolean
sanket = np.array([1,0,3])
sanket1 = sanket.astype(bool)
print(sanket1)
print(sanket1.dtype)

[ True False  True]
bool


In [ ]:
# List of all datatypes in the numpy
# i -- integer
# b -- boolean
# u -- unsigned integer
# f -- for float
# c -- complex float
# m -- timedelta
# M -- datatime
# O -- object
# S -- string
# U -- Unicode string

In [ ]:
## Difference between the copy & the view of array command
# -- the copy is the new array while a view is just the view of the original array.
# -- any changes made in the copy array will not affect the original array and vice versa.
# -- view does not own any data and any changes made to the view will affect the original data.

In [1]:
# Example of copy -- changes in the copy will not affect the original array
import numpy as np
sanket = np.array([1,2,3,4,5])
x = sanket.copy()
sanket[0] = 42
print(sanket)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [2]:
# Example of view -- change in the view will affect the original array
sanket = np.array([1,2,3,4,5])
x = sanket.view()
sanket[0] = 42
print(sanket)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [3]:
# Check if arrays owns its data
# copies own data while view does not own data -- how to check it
# every numpy array has a attribute base it return none if the array dies not own the data
# print the value of the base attribute to check if an array own it's data or not
sanket = np.array([1,2,3,4,5])
x = sanket.copy()
y = sanket.view()

print(x.base) # none -- means copy does not return anything -- it is just copy it does not own the data.
print(y.base) # view returns the array means it is affected by the original array.


None
[1 2 3 4 5]


In [6]:
# How to judge the shape of the numpy array's.
# the shape of the array is the number of element in each dimension -- how we can get the shape of the numpy array -- numpy 
# has an shape attribute that return tuple with each index having the number of corresponding elements.
# How to print the shape of the 2D array
sanket = np.array([[1,2,3,4],[5,6,7,8]])
# I want to know its shape 
print(sanket.shape)
# it has given result as 2,4 here 2,4 means the array has 2 dimensions and the first dimension has two elements and the 
# second dimension has the 4 elements.
# 1st dimension -- [1,2,3,4]
# 2nd dimension -- [5,6,7,8]

(2, 4)


In [8]:
sanket = np.array([1,2,3,4,5],ndmin=5)
print(sanket)
print(sanket.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


In [9]:
# How to reshape an array -- reshaping means changing the shape of the array -- shape of array means the number of elements
# in each dimension -- by reshaping we can add or remove dimension or we can change the number elements in the each dimensn
# Suppose I want to reshape from 1D to the 2D
sanket = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
# above is the one-D and I want to change it to the 2D. --  I have given 12 values I want to change it to 2D -- but how
# I will change the outermost diimension so that it will have 4 arrays with 3 elemetns each
sanketnew = sanket.reshape(4,3) # means the 4 rows with the 3 columns.
print(sanketnew)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
# Now convert it into the 3D 
sanket = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
sanketnew = sanket.reshape(2,3,2) 
print(sanketnew)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# can we reshape into any shape -- as long as the elements required for reshaping are equal in both shapes -- if u hv total
# 10 elements and you want to reshape it into 50 then how it is possible -- it is not possible -- you can divide it into
# 2,2 or 12 but you can't divide into 15 or twelve bcz the number of elements is not sufficient. -- like we can rshape 8 ele
# into 1D array like means 4 elements in two rows but we cannot reshape into three element bcz 8/3 not possible. 

In [13]:
# Convert 1D array with 8 elements to 2D array with 3 elements in each dimension
sanket = np.array([1,2,3,4,5,6,7,8])
# I want to convert it into 3,3 3 arrays with 3 elements each
sanketnew = sanket.reshape(3,3) # it will show the error
print(sanketnew)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [15]:
# if  i want to convert this 8 elements into the 3D then I can do so 
# converting 2D array of 8 elements into 3D -- by 2,2
sanket = np.array([1,2,3,4,5,6,7,8])
sanketnew = sanket.reshape(2,2,-1) # -1 for the unknown dimension
print(sanketnew)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
# Flattening array -- means converting the multidimensional array into 1D array.
# eg.
sanket = np.array([[1,2,3],[4,5,6]])
sanketnew = sanket.reshape(-1)
print(sanketnew)

[1 2 3 4 5 6]


In [18]:
# Numpy array iterating 
# Iterating over 1D array.
sanket = np.array([1,2,3])
for x in sanket:
    print(x)

1
2
3


In [19]:
# Iterating over 2D array
sanket = np.array([[1,2,3],[4,5,6]])
for x in sanket:
    print(x)

[1 2 3]
[4 5 6]


In [21]:
# Iterating on each scaler element of the 2D array
sanket = np.array([[1,2,3],[4,5,6]])
for x in sanket:
    for y in x:
        print(y,end=" ")

1 2 3 4 5 6 

In [22]:
# How to iterate over 3D array
sanket = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for x in sanket:
    print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
# Iterate over 3D array
sanket = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
for x in sanket:
    for y in x:
        for i in y:
            print(i,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [28]:
# Iterate over array using nditer() -- helping function use for from basic to advance iteration
# Iterate over 3D array by using the nditer
sanket = np.array([[[1,2],[3,4],[5,6],[7,8]]])
for x in np.nditer(sanket):
    print(x,end=" ")

1 2 3 4 5 6 7 8 

In [ ]:
# Joining the numpy array's -- means putting the content of two or more array's in the single array's.
# In SQL we join tables by the key while in the numpy we jion the array by using the axis. -- both are same.
# we use concat function for that purpose -- along with the axis -- by default axis is the 0.
# Join the two array's.

In [30]:
sanket1 = np.array([1,2,3])
sanket2 = np.array([4,5,6])
sanket3 = np.concatenate((sanket1,sanket2)) # Pass the arguments 
print(sanket3)

[1 2 3 4 5 6]


In [35]:
# Concatnating / joining 2 2D arrays along with rows (axis=1)
sanket1 = np.array([[1,2],[3,4]])
sanket2 = np.array([[5,6],[7,8]])
sanket3 = np.concatenate((sanket1,sanket2),axis=1)
print(sanket3)

[[1 2 5 6]
 [3 4 7 8]]


In [36]:
sanket1 = np.array([[1,2],[3,4]])
sanket2 = np.array([[5,6],[7,8]])
sanket3 = np.concatenate((sanket1,sanket2),axis=0)
print(sanket3)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [38]:
# Joining the arrays using the stack function -- stack function is same as concatenate function the pnly difference is that 
# stacking is done along the new axis. 
sanket1 = np.array([1,2,3])
sanket2 = np.array([4,5,6])
sanket3 = np.stack((sanket1,sanket2),axis=1)
print(sanket3)

[[1 4]
 [2 5]
 [3 6]]


In [41]:
# Different type of stack -- there are two types of stack -- stack along row's and the stack along column's.
sanket1 = np.array([1,2,3])
sanket2 = np.array([4,5,6])
sanket3 = np.hstack((sanket1,sanket2)) # hstack for stacking via row.
sanket4 = np.vstack((sanket1,sanket2)) # vstack for stacking along the column's.
sanket5 = np.dstack((sanket1,sanket2)) # dstack for stacking along the height.
print(sanket3)
print(sanket4)
print(sanket5)
# stack gives more functionality rather than join so use stack.

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
# Numpy splitting the array -- How to splitting -- splitting is the reverse operation of the joining -- splitting breaks 
# the one array into multiple array.
# we will array_split() function

In [42]:
sanket = np.array([1,2,3,4,5,6])
sanketnew = np.array_split(sanket,3)
print(sanketnew) # all are the 1D array's.

[array([1, 2]), array([3, 4]), array([5, 6])]


In [43]:
# above there are 6 elements so divided into 3 parts containing 2 value each -- if an array has odd numbers then it will be
# adjusted by the last element. 
# what if the elements are less 
sanket = np.array([1,2,3,4,5,6])
sanketnew = np.array_split(sanket,4)
print(sanketnew)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [44]:
# Dont use split() function always use the array_split() function as split method does not adjust if vslues are less then 
# use the array_split function.
sanket = np.array([1,2,3,4,5,6])
sanketnew = np.array_split(sanket,3)
print(sanketnew)
# Now I want to access the only first array
print(sanketnew[0])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]


In [45]:
# Till now we have seen how to see the 1D array now we will see how to split the 2D array.
# Splitting 2D array
sanket = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
sanketnew = np.array_split(sanket,3)
print(sanketnew) # here array was divided into the three parts

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [46]:
sanket = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
sanketnew = np.array_split(sanket,4)
print(sanketnew)
# array([[1, 2],[3, 4]]), 
# array([[5, 6],[7, 8]]), 
# array([[ 9, 10]]), 
# array([[11, 12]])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [47]:
# Split the 2D array into three 2D but as per rows
sanket = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
sanketnew = np.array_split(sanket,3,axis=1)
print(sanketnew)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [50]:
# using the hsplit method to split the 2D array into the three 2D array along with the row's.
sanket = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
sanketnew = np.hsplit(sanket,3)
print(sanketnew)
# hsplit doing the same as the array_split method -- but always use the array_split.

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [51]:
# Searching Array
# You can search an array for a certian value and you can return indexes that get the match -- for searching the array we
# use where() method.
sanket = np.array([1,2,3,4,5])
x = np.where(sanket == 4)
print(x)

(array([3], dtype=int64),)


In [3]:
# we will find the index where values are even
import numpy as np
sanket = np.array([1,2,3,4,5,7,8])
x = np.where(sanket%2 == 0)
print(x)

(array([1, 3, 6], dtype=int64),)


In [2]:
# find the index where values are the odd
import numpy as np
sanket = np.array([1,2,3,4,5,7,8])
x = np.where(sanket%2 != 0)
print(x)

(array([0, 2, 4, 5], dtype=int64),)


In [ ]:
# searchsorted() method  -- it start the search from the left to right -- where we can insert 
# specified value in the array
sanket = np.array([6,7,8,9])
x = np.searchsorted(sanket,7)  # Finding the index number of the specified value in the array
print(x)

In [5]:
# How to start searching from the right to left
sanket = np.array([6,7,8,9])
x = np.searchsorted(sanket,7,side='right') # so from right 7 is on the 2 index number
print(x)

2


In [6]:
# Seaching the multiple values 
sanket = np.array([1,3,5,7])
x = np.searchsorted(sanket,[2,4,6]) #from where to search, what to search
print(x)

[1 2 3]


In [7]:
# How to sort array in the numpy -- use sort() function for that purpose
sanket  = np.array([3,2,0,1])
print(np.sort(sanket)) #sort method just returns the copy of the array and it does not change the original array

[0 1 2 3]


In [8]:
# we can sort any data type
sanket  = np.array(['r','f','t','h'])
print(np.sort(sanket))

['f' 'h' 'r' 't']


In [9]:
# Sorting the 2D array -- till now we have seen 1D array -- sorting can be done on any dimension
sanket = np.array([[3,2,4],[5,0,1]])
print(np.sort(sanket))

[[2 3 4]
 [0 1 5]]


In [11]:
# How filter array in the numpy -- getting some elements out of the array and creating the new array is the filtering -- in
# numpy we can use filter and array using boolean index list -- bolleans index list is the list of the boolean corresponding
# to the inndexes in the array's
sanket = np.array([41,42,43,44])
x = [True,False,True,False]
sanketnew = sanket[x]
print(sanketnew)

[41 43]


In [13]:
# Creating the filter array
sanket = np.array([41,42,43,44])
# create an empty list 
sanketf = []
# go through each element in the array -- if element is higher than 42 then True otherwise False
for i in sanket:
        if i > 42:
            sanketf.append(True)
        else:
            sanketf.append(False)
print(sanketf)

[False, False, True, True]


In [14]:
# Numpy Random Number's 
# This random number is generated though algorithm called pseudo random
from numpy import random
sanket = random.randint(100)
print(sanket)

18


In [15]:
# random float
x = random.rand()
print(x)

0.3329507632812191


In [16]:
# Generate random array's
# 1D Array
sanket = random.randint(100,size=(5))
print(sanket)

[74 25 35 88 28]


In [17]:
# Create 2D array 
sanket = random.randint(100,size=(3,5))
print(sanket)

[[88 49 35 56 73]
 [13 50 62 81  6]
 [54 75 19 57 52]]


In [20]:
# Create floating 1D array
sanket = random.rand(5)
print(sanket)

[0.18204825 0.58975203 0.95325934 0.37829727 0.36539829]


In [21]:
# Create 2D Floating array
sanket = random.rand(3,5)
print(sanket)

[[0.33183997 0.4829109  0.90090645 0.91543944 0.86423466]
 [0.83517671 0.26512093 0.22589222 0.03247428 0.24495387]
 [0.38628717 0.94003674 0.31052217 0.24593498 0.62104455]]


In [22]:
# Generate Random Number from an Array
# we will use choice function
sanket = random.choice([3,5,7,9])
print(sanket)

9


In [23]:
# Generate 2D From the random array
sanket = random.choice([3,5,7,9],size=(3,5))
print(sanket)

[[9 3 7 5 9]
 [7 3 3 9 9]
 [3 9 9 7 7]]
